# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  config.vm.box = "ubuntu12"
  config.vm.provision 'shell', path: 'provision.sh'
  config.vm.network "forwarded_port", guest: 8080, host: 8182
  # config.vm.network "private_network", ip: "192.168.33.10"

  # config.vm.synced_folder "../data", "/vagrant_data"

end
